# coding: utf-8

# flake8: noqa

"""
    CrowdSorcerer Ingest API

    The Ingest API for data ingestion into the data lake.  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from crowdsorcerer_client_ingest.api.data_deletion_api import DataDeletionApi
from crowdsorcerer_client_ingest.api.data_upload_api import DataUploadApi
# import ApiClient
from crowdsorcerer_client_ingest.api_client import ApiClient
from crowdsorcerer_client_ingest.configuration import Configuration
# import models into sdk package
