# coding: utf-8

"""
    CrowdSorcerer Ingest API

    The Ingest API for data ingestion into the data lake (WIP).  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.data_upload_api import DataUploadApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDataUploadApi(unittest.TestCase):
    """DataUploadApi unit test stubs"""

    def setUp(self):
        self.api = DataUploadApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_data_upload(self):
        """Test case for data_upload

        Upload Home data linked to an UUID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
