# coding: utf-8

# flake8: noqa
"""
    CrowdSorcerer Ingest API

    The Ingest API for data ingestion into the data lake.  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
