# coding: utf-8

"""
    CrowdSorcerer Ingest API

    The Ingest API for data ingestion into the data lake.  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from crowdsorcerer_client_ingest.api_client import ApiClient


class DataDeletionApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def data_deletion(self, home_uuid, **kwargs):  # noqa: E501
        """Clear Home data linked to an UUID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.data_deletion(home_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str home_uuid: This home's UUID (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.data_deletion_with_http_info(home_uuid, **kwargs)  # noqa: E501
        else:
            (data) = self.data_deletion_with_http_info(home_uuid, **kwargs)  # noqa: E501
            return data

    def data_deletion_with_http_info(self, home_uuid, **kwargs):  # noqa: E501
        """Clear Home data linked to an UUID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.data_deletion_with_http_info(home_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str home_uuid: This home's UUID (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['home_uuid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method data_deletion" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'home_uuid' is set
        if ('home_uuid' not in params or
                params['home_uuid'] is None):
            raise ValueError("Missing the required parameter `home_uuid` when calling `data_deletion`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}
        if 'home_uuid' in params:
            header_params['Home_UUID'] = params['home_uuid']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/data', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
